#!/usr/bin/env bash
#display info about sub-domain
domain_name=$1 
if [ "$#" -eq 2 ]; then
	sub_domain=$2
else
	sub_domain=("www" "lb-01" "web-01" "web-02")
fi
for sub in "${sub_domain[@]}"; do
	echo -n "The subdomain $sub"
	dig "$sub.$domain_name" | grep -A1 'ANSWER SECTION:' | tail -n -1 | awk '{print " is a " $4 " record and points to " $5}'
done
